### ISSUE TITLE
install.sh builds 'version2' of top-level project

### ISSUE THREAD

**Issue by veox** [libbitcoin/libbitcoin-build#42]
Building `libbitcoin-explorer` using `install.sh` has recently resulted in failure for me (after branch 'bip39' was merged in). In that scenario, `libbitcoin` 'master' was built, whereas `libbitcoin-explorer` was still 'version2'.

Cloning git and then building the more stable version seems counter-intuitive. I've previously been modifying the `install.sh` script manually to build 'master' instead.

Will provide a PR. However, this might be intended, so let's discuss it first.

**Comment by veox** [comment]
P.S. not sure how to handle the case where someone clones git, checks out branch 'version2', and expects 'version2' to be built when calling `install.sh`.

**Comment by evoskuil** [comment]
Master is considered staging and currently master is all building against master because there are required changes in contrast to version2. BX should have been set to pull master as well until these changes are pushed into version2. It doesn't break in Travis since the primary repo is not pulled from the install script.

**Comment by evoskuil** [comment]
install.sh builds the repo that it is cloned from when building in Travis, but it doesn't assume that any repo has been cloned otherwise. So it builds whatever repo it has been configured to build. Generally I leave this as the most recent released branch, so someone can simply get the install.sh and run it. To ensure the quality of the install we run the installer as the Travis build, but in the case where we have coordinated changes across repos we have a conflict between those two objectives. So I've dealt with this by considering that master is always staging and documenting the version2 install.sh as the one people should build from if they don't want to be on the bleeding edge.

**Comment by veox** [comment]
Ah, OK. Building 'version2' everywhere works OK, too.

**Comment by evoskuil** [comment]
Once the latest wave of generated code changes make their way through Travis I'll be pushing everything to version2 branches and will update -build and the installers accordingly. Once that clears Travis I'll start tagging the releases.
